arch:
- amd64
codenotary: velovec@gmail.com
description: SuperFleet Home Assistant Add-On
image: docker.velovec.pro/hassio-addons/transmission/{arch}
init: false
name: SuperFleet
ports:
  8080/tcp: null
  1488/tcp: null
ports_description:
  8080/tcp: REST API
  1488/tcp: SSH-based CLI
map:
  - share:rw
options:
  rabbitmq:
    host: localhost
    port: 5673
    user: guest
    password: guest
  database:
    url: jdbc:postgresql://postgres:5432/superfleet
    username: postgres
    password: P@ssw0rd
schema:
  rabbitmq:
    host: str
    port: port
    user: str
    password: password
  database:
    url: str
    username: str
    password: password
slug: superfleet
url: https://github.com/velovec/hassio-addons-repository
version: latest
